Pipfile: Upgrade strawberry-graphql
The next version will cause a type error

projectify/views.py:38: error: Missing type parameters for generic type "GraphQLView"  [type-arg]